export type ErrorCode = number;

const NO_ERROR = 0;
const REQUEST_HAS_WRONG_INTERRUPT_NR_ERROR_CODE = 1;
const REQUEST_HAS_UN_EXISTING_MOMENT_ERROR_CODE = 2;
const REQUEST_HAS_UNEXISTING_ADDR_ERROR_CODE = 3;
const COULD_NOT_ADD_HOOK_ERROR_CODE = 4;
const COULD_NOT_REMOVE_HOOK_ERROR_CODE = 5;

// Error codes of remote call request
// const REMOTE_CALL_ERROR_CODE_OUT_OF_MEMORY = 1;
const REMOTE_CALL_ERROR_CODE_READ_FROM_CLIENT = 11;
const REMOTE_CALL_ERROR_CODE_WRITE_TO_CLIENT = 11;
const REMOTE_CALL_ERROR_CODE_CLIENT_REPLY_TOO_LARGE = 12;
const REMOTE_CALL_ERROR_CODE_CLIENT_CLOSED = 13;
const REMOTE_CALL_ERROR_CODE_INVALID_FUNCTION = 20;
const REMOTE_CALL_ERROR_CODE_MALFORMED_FUNCTION_ARGS = 21;
const REMOTE_CALL_ERROR_CODE_INVALID_NUMBER_OF_ARGUMENTS = 22;
const REMOTE_CALL_ERROR_CODE_MALFORMED_RESPONSE = 30;
const REMOTE_CALL_ERROR_CODE_MALFORMED_REQUEST_INTERRUPT_NR = 31;

const UPDATE_GLOBAL_VALUE_WRONG_INDEX_ERROR_CODE = 90;
const UPDATE_STACK_VALUE_WRONG_INDEX_ERROR_CODE = 91;
const UPDATE_STACK_VALUE_INVALID_DESERIALISE_ERROR_CODE = 92;

const HANDLE_INVOKE_NO_FUNC_WITH_GIVEN_ID_ERROR_CODE = 93;
const UPDATE_LOCAL_INVALID_INTERRUPT_NR = 94;

const errorMessages = new Map<ErrorCode, string>([
  [NO_ERROR, 'No error occurred'],
  [REQUEST_HAS_WRONG_INTERRUPT_NR_ERROR_CODE, ''],
  [
    REQUEST_HAS_UN_EXISTING_MOMENT_ERROR_CODE,
    'Request does not support the provided Hook Mode',
  ],
  [
    REQUEST_HAS_UNEXISTING_ADDR_ERROR_CODE,
    'REQUEST_HAS_UNEXISTING_ADDR_ERROR_CODE',
  ],
  [COULD_NOT_ADD_HOOK_ERROR_CODE, 'COULD_NOT_ADD_HOOK_ERROR_CODE'],
  [COULD_NOT_REMOVE_HOOK_ERROR_CODE, 'COULD_NOT_REMOVE_HOOK_ERROR_CODE'],
  // [
  //   REMOTE_CALL_ERROR_CODE_OUT_OF_MEMORY,
  //   'REMOTE_CALL_ERROR_CODE_OUT_OF_MEMORY',
  // ],
  [
    REMOTE_CALL_ERROR_CODE_READ_FROM_CLIENT,
    'REMOTE_CALL_ERROR_CODE_READ_FROM_CLIENT',
  ],
  [
    REMOTE_CALL_ERROR_CODE_WRITE_TO_CLIENT,
    'REMOTE_CALL_ERROR_CODE_WRITE_TO_CLIENT',
  ],
  [
    REMOTE_CALL_ERROR_CODE_CLIENT_REPLY_TOO_LARGE,
    'REMOTE_CALL_ERROR_CODE_CLIENT_REPLY_TOO_LARGE',
  ],
  [
    REMOTE_CALL_ERROR_CODE_CLIENT_CLOSED,
    'REMOTE_CALL_ERROR_CODE_CLIENT_CLOSED',
  ],
  [
    REMOTE_CALL_ERROR_CODE_INVALID_FUNCTION,
    'REMOTE_CALL_ERROR_CODE_INVALID_FUNCTION',
  ],
  [
    REMOTE_CALL_ERROR_CODE_MALFORMED_FUNCTION_ARGS,
    'REMOTE_CALL_ERROR_CODE_MALFORMED_FUNCTION_ARGS',
  ],
  [
    REMOTE_CALL_ERROR_CODE_INVALID_NUMBER_OF_ARGUMENTS,
    'REMOTE_CALL_ERROR_CODE_INVALID_NUMBER_OF_ARGUMENTS',
  ],
  [
    REMOTE_CALL_ERROR_CODE_MALFORMED_RESPONSE,
    'REMOTE_CALL_ERROR_CODE_MALFORMED_RESPONSE',
  ],
  [
    REMOTE_CALL_ERROR_CODE_MALFORMED_REQUEST_INTERRUPT_NR,
    'REMOTE_CALL_ERROR_CODE_MALFORMED_REQUEST_INTERRUPT_NR',
  ],
  [
    UPDATE_GLOBAL_VALUE_WRONG_INDEX_ERROR_CODE,
    'the provided global value index does not exist',
  ],
  [
    UPDATE_STACK_VALUE_WRONG_INDEX_ERROR_CODE,
    'the provided stack value index does not exist',
  ],
  [
    UPDATE_STACK_VALUE_INVALID_DESERIALISE_ERROR_CODE,
    'the provided stack value cannot be deserialised',
  ],

  [
    HANDLE_INVOKE_NO_FUNC_WITH_GIVEN_ID_ERROR_CODE,
    'the provided function ID is not part of teh functions',
  ],
  [
    UPDATE_LOCAL_INVALID_INTERRUPT_NR,
    'when updating locals a wrong interrupt nr was passed',
  ],
]);

export function errorCodeToMessage(errorCode: ErrorCode): string | undefined {
  return errorMessages.get(errorCode);
}
