name: Lint check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Fail on Linting Errors
        run: |
          if [ ${{ failure() }} == true ]; then
            echo "Linting failed, failing the workflow."
            exit 1
          fi
