name: wasmito Tests

on: [ push ]

jobs:
  test-wasmito:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build warduino cli
        run: |
            git clone --recursive https://github.com/carllocos/WARDuino.git
            cd WARDuino
            mkdir build-emu
            cd build-emu
            cmake .. . -DBUILD_EMULATOR=ON
            make
            cd ..
            echo "WARDUINO_PATH=$(realpath .)" >> $GITHUB_ENV
            echo $WARDUINO_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: build TS
        run: npx tsc

      - name: yarn install and test
        run: |
          yarn 
          WARDUINO_SDK=$WARDUINO_PATH yarn test
