name: wasmito Tests

on: [push]

jobs:
  test-wasmito:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust and wasm32 targets
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env" 
          rustup target add wasm32-unknown-unknown

      - name: Install cargo-binstall
        run: cargo install cargo-binstall

      - name: Install wasm-tools
        run: cargo binstall wasm-tools

      - name: Build submodules
        run: |
          echo "Running installation script"
          bash ./install.sh

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: build TS
        run: npx tsc

      - name: yarn install and test
        run: |
          yarn 
          yarn test
