name: wasmito Tests

on: [ push ]

jobs:
  test-wasmito:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build submodules
        run: |
            echo "Running installation script"
            bash ./install.sh

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: build TS
        run: npx tsc

      - name: yarn install and test
        run: |
          yarn 
          yarn test
